### ISSUE TITLE
Add download script?

### ISSUE THREAD

**Issue by jaredmoody** [Sija/crystal-dash-docset#1]
I just used this repo to submit a PR to update the crystal docs to 0.35.1, thanks!

What do you think about including code to download the website - I don't own SiteSucker, so I used this wget script:

```
wget \
  --recursive \
  --no-clobber \
  --page-requisites \
  --html-extension \
  --convert-links \
  --domains crystal-lang.org \
  --no-host-directories \
  --no-parent \
  crystal-lang.org/reference/, crystal-lang.org/api/
```

Perhaps it could be included as ./download.sh if you don't want to include it in ./build.sh

**Comment by Sija** [comment]
@jaredmoody Good idea! Taking it even further it could be automated to generate the docset directly within the CI pipeline.

**Comment by Sija** [comment]
@jaredmoody Howdy! Could you please double check whether the produced docset [artifact](https://github.com/Sija/crystal-dash-docset/actions/runs/731145915#artifacts) is indeed correct?

**Comment by jaredmoody** [comment]
LGTM! 👍🏼

Is there a way to have the artifact published as a release or otherwise added to the main page? The README needs updating too now that you don't have to build the docset yourself.

**Comment by Sija** [comment]
ATM the workflow is triggered manually but I guess it could be enhanced with publishing artifacts as releases 👍

**Comment by jaredmoody** [comment]
It may not be worth automating, was just a thought.

Would be nice to direct people to that built artifact from the main page somehow though

**Comment by Sija** [comment]
@jaredmoody Thanks for suggestion! And so releases are now automated - you can already find there docsets for the last two Crystal versions, cheers!
